import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "deep-navy": "#0A1128",
        "champagne-gold": "#D4AF37",
        "surface-tint": "#585d75",
        "on-secondary-fixed": "#241a00",
        "on-tertiary-container": "#828485",
        "on-tertiary-fixed-variant": "#454748",
        "secondary": "#745b00",
        "on-background": "#111c2c",
        "tertiary-fixed": "#e1e3e4",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9ff",
        "surface-container": "#e7eeff",
        "on-secondary": "#ffffff",
        "on-surface": "#111c2c",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#191c1d",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "tertiary-container": "#191c1d",
        "secondary-fixed": "#ffe089",
        "inverse-primary": "#c0c5e1",
        "surface-variant": "#d8e3fa",
        "primary": "#000000",
        "on-secondary-container": "#725a00",
        "secondary-fixed-dim": "#eac243",
        "surface-container-highest": "#d8e3fa",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-primary-fixed-variant": "#40465c",
        "background": "#f9f9ff",
        "primary-fixed-dim": "#c0c5e1",
        "secondary-container": "#fcd353",
        "primary-container": "#151b2f",
        "error": "#ba1a1a",
        "outline": "#76767d",
        "on-surface-variant": "#46464d",
        "inverse-surface": "#263142",
        "primary-fixed": "#dce1fd",
        "on-primary-container": "#7d839c",
        "inverse-on-surface": "#ebf1ff",
        "outline-variant": "#c7c6cd",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-high": "#dee8ff",
        "on-primary-fixed": "#151b2f",
        "surface-dim": "#cfdaf1",
        "surface": "#f9f9ff",
        "on-error-container": "#93000a"
      },
      spacing: {
        "sidebar-width": "260px",
        "unit-xs": "4px",
        "unit-xl": "48px",
        "unit-md": "16px",
        "sidebar-collapsed": "72px",
        "header-height": "64px",
        "unit-lg": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "unit-sm": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-ui": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "body-doc": ["Source Serif 4"],
        "headline-sm": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-ui": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-doc": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-lg": ["30px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
