'use server';

import { revalidatePath } from 'next/cache';

import { prisma } from '@/lib/prisma/client';
import { Prisma } from '@prisma/client';
import { getCurrentUserId, requireRole } from '@/lib/supabase/get-current-user-role';

type CreateInvoiceInput = {
  invoiceNumber: string;
  matterId: string;
  clientName?: string;
  amount?: number;
  dueDateLabel?: string;
  status?: Prisma.InvoiceUncheckedCreateInput['status'];
  notes?: string;
  lineItems?: Array<{
    description: string;
    hours: number;
    rate: number;
    total: number;
  }>;
};

export async function createInvoice(data: CreateInvoiceInput) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false as const, error: 'FORBIDDEN', message: 'Forbidden' };
  const userId = await getCurrentUserId();
  const invoiceNumber = String(data.invoiceNumber ?? '').trim();
  const matterId = String(data.matterId ?? '').trim();

  if (!invoiceNumber || !matterId) {
    return { success: false as const, error: 'VALIDATION', message: 'Missing invoice number or matter selection.' };
  }

  try {
    const created = await prisma.invoice.create({
      data: {
        userId,
        invoiceNumber,
        matterId,
        clientName: String(data.clientName ?? ''),
        amount: new Prisma.Decimal(Number(data.amount) || 0),
        dueDateLabel: String(data.dueDateLabel ?? ''),
        notes: data.notes,
        status: 'Draft',
        lineItems: data.lineItems?.length
          ? {
              create: data.lineItems.map((li) => ({
                description: li.description,
                hours: new Prisma.Decimal(li.hours),
                rate: new Prisma.Decimal(li.rate),
                total: new Prisma.Decimal(li.total),
              })),
            }
          : undefined,
      },
      include: { lineItems: true },
    });

    revalidatePath('/billing');
    revalidatePath(`/billing/${created.id}`);

    return {
      success: true as const,
      invoice: {
        id: created.id,
        invoiceNumber: created.invoiceNumber,
        matterId: created.matterId,
        clientName: created.clientName,
        amount: Number(created.amount),
        dueDateLabel: created.dueDateLabel,
        status: created.status,
        createdAt: created.createdAt instanceof Date ? created.createdAt.toISOString() : String(created.createdAt),
      },
    };
  } catch (error) {
    console.error("Prisma Error Details:", error);

    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === 'P2002') {
        return {
          success: false as const,
          error: 'DUPLICATE_INVOICE',
          message: `Invoice number "${invoiceNumber}" already exists for this matter. Please use a different invoice number.`,
        };
      }
      if (error.code === 'P2003') {
        return {
          success: false as const,
          error: 'INVALID_MATTER',
          message: 'The selected matter does not exist. Please choose a valid matter from the list.',
        };
      }
    }

    return { success: false as const, error: 'UNKNOWN', message: 'Database transmission failed. Please inspect input formats.' };
  }
}

export async function getInvoiceById(id: string) {
  const userId = await getCurrentUserId();
  try {
    const row = await prisma.invoice.findFirst({
      where: { id, userId },
      include: {
        matter: {
          select: {
            title: true,
            clientId: true,
            client: {
              select: {
                billingAddress: true,
                email: true,
                phone: true,
              },
            },
          },
        },
        lineItems: true,
      },
    });
    if (!row) return null;
    const clientBillingAddr = row.matter.client?.billingAddress;
    return {
      id: row.id,
      invoiceNumber: row.invoiceNumber,
      matterId: row.matterId,
      clientId: row.matter.clientId,
      matterTitle: row.matter.title,
      clientName: row.clientName,
      amount: Number(row.amount),
      dueDateLabel: row.dueDateLabel,
      status: row.status,
      autoGenerated: row.autoGenerated,
      billingPeriodStart: row.billingPeriodStart?.toISOString() ?? null,
      billingPeriodEnd: row.billingPeriodEnd?.toISOString() ?? null,
      createdAt: row.createdAt instanceof Date ? row.createdAt.toISOString() : String(row.createdAt),
      approvedAt: row.approvedAt instanceof Date ? row.approvedAt.toISOString() : null,
      notes: row.notes,
      clientAddress: clientBillingAddr ? (typeof clientBillingAddr === 'string' ? clientBillingAddr : JSON.stringify(clientBillingAddr)) : null,
      clientEmail: row.matter.client?.email ?? null,
      clientPhone: row.matter.client?.phone ?? null,
      lineItems: row.lineItems.map((li) => ({
        id: li.id,
        description: li.description,
        hours: Number(li.hours),
        rate: Number(li.rate),
        total: Number(li.total),
      })),
    };
  } catch (error) {
    console.error('Failed to fetch invoice:', error);
    return null;
  }
}

export async function updateInvoiceClientInfo(invoiceId: string, data: { address?: string; email?: string; phone?: string }) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false, message: 'Forbidden' };
  const userId = await getCurrentUserId();
  try {
    const inv = await prisma.invoice.findFirst({
      where: { id: invoiceId, userId },
      include: { matter: { select: { clientId: true } } },
    });
    if (!inv) return { success: false, message: 'Invoice not found' };

    const clientId = inv.matter.clientId;
    if (!clientId) return { success: false, message: 'No client associated with this matter' };

    const updateData: Record<string, unknown> = {};
    if (data.email !== undefined) updateData.email = data.email;
    if (data.phone !== undefined) updateData.phone = data.phone;
    if (data.address !== undefined) updateData.billingAddress = data.address;

    await prisma.client.update({
      where: { id: clientId },
      data: updateData,
    });

    revalidatePath('/billing');
    revalidatePath(`/billing/${invoiceId}`);
    return { success: true, message: 'Client info updated' };
  } catch (error) {
    console.error('updateInvoiceClientInfo error:', error);
    return { success: false, message: 'Failed to update client info' };
  }
}

export async function approveInvoice(invoiceId: string) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false as const, error: 'FORBIDDEN', message: 'Forbidden' };
  const userId = await getCurrentUserId();
  try {
    const inv = await prisma.invoice.findFirst({ where: { id: invoiceId, userId } });
    if (!inv) return { success: false as const, error: 'NOT_FOUND', message: 'Invoice not found.' };
    await prisma.$transaction([
      prisma.invoice.update({
        where: { id: invoiceId },
        data: {
          status: 'PendingApproval',
          approvedAt: new Date(),
        },
      }),
      prisma.invoiceApproval.create({
        data: {
          invoiceId,
          approverName: 'System',
          decision: 'approved',
        },
      }),
    ]);
    revalidatePath('/billing');
    revalidatePath(`/billing/${invoiceId}`);
    return { success: true as const, message: 'Invoice submitted for approval.' };
  } catch (error) {
    console.error('Failed to approve invoice:', error);
    return { success: false as const, error: 'UNKNOWN', message: 'Failed to submit invoice for approval.' };
  }
}

export async function finalizeInvoice(invoiceId: string) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false as const, error: 'FORBIDDEN', message: 'Forbidden' };
  const userId = await getCurrentUserId();
  try {
    const inv = await prisma.invoice.findFirst({ where: { id: invoiceId, userId } });
    if (!inv) return { success: false as const, error: 'NOT_FOUND', message: 'Invoice not found.' };
    await prisma.invoice.update({
      where: { id: invoiceId },
      data: { status: 'Finalized' },
    });
    revalidatePath('/billing');
    revalidatePath(`/billing/${invoiceId}`);
    return { success: true as const, message: 'Invoice finalized successfully.' };
  } catch (error) {
    console.error('Failed to finalize invoice:', error);
    return { success: false as const, error: 'UNKNOWN', message: 'Failed to finalize invoice.' };
  }
}

export async function rejectInvoice(invoiceId: string) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false as const, error: 'FORBIDDEN', message: 'Forbidden' };
  const userId = await getCurrentUserId();
  try {
    const inv = await prisma.invoice.findFirst({ where: { id: invoiceId, userId } });
    if (!inv) return { success: false as const, error: 'NOT_FOUND', message: 'Invoice not found.' };
    await prisma.$transaction([
      prisma.invoice.update({
        where: { id: invoiceId },
        data: { status: 'Draft' },
      }),
      prisma.invoiceApproval.create({
        data: {
          invoiceId,
          approverName: 'System',
          decision: 'rejected',
        },
      }),
    ]);
    revalidatePath('/billing');
    revalidatePath(`/billing/${invoiceId}`);
    revalidatePath('/billing/approvals');
    return { success: true as const, message: 'Invoice rejected and returned to draft.' };
  } catch (error) {
    console.error('Failed to reject invoice:', error);
    return { success: false as const, error: 'UNKNOWN', message: 'Failed to reject invoice.' };
  }
}

export async function markAsPaid(invoiceId: string) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false as const, error: 'FORBIDDEN', message: 'Forbidden' };
  const userId = await getCurrentUserId();
  try {
    const inv = await prisma.invoice.findFirst({ where: { id: invoiceId, userId } });
    if (!inv) return { success: false as const, error: 'NOT_FOUND', message: 'Invoice not found.' };
    await prisma.invoice.update({
      where: { id: invoiceId },
      data: { status: 'Paid' },
    });
    revalidatePath('/billing');
    revalidatePath(`/billing/${invoiceId}`);
    return { success: true as const, message: 'Invoice marked as paid.' };
  } catch (error) {
    console.error('Failed to mark invoice as paid:', error);
    return { success: false as const, error: 'UNKNOWN', message: 'Failed to mark invoice as paid.' };
  }
}

export async function getBillingMetrics() {
  const userId = await getCurrentUserId();
  try {
    const allInvoices = await prisma.invoice.findMany({
      where: { userId },
      select: { amount: true, status: true, createdAt: true, approvedAt: true },
    });

    const now = new Date();
    const startOfYear = new Date(now.getFullYear(), 0, 1);

    let outstanding = 0;
    let ytdTotal = 0;
    let draftCount = 0;
    const paymentDays: number[] = [];

    for (const inv of allInvoices) {
      const amt = Number(inv.amount);
      if (inv.status === 'Draft' || inv.status === 'PendingApproval') {
        outstanding += amt;
      }
      if ((inv.status === 'Paid' || inv.status === 'Finalized') && inv.approvedAt) {
        const days = Math.round((inv.approvedAt.getTime() - inv.createdAt.getTime()) / (1000 * 60 * 60 * 24));
        paymentDays.push(days);
      }
      if (inv.createdAt >= startOfYear) {
        ytdTotal += amt;
      }
      if (inv.status === 'Draft') {
        draftCount++;
      }
    }

    const avgDays = paymentDays.length > 0
      ? Math.round(paymentDays.reduce((a, b) => a + b, 0) / paymentDays.length)
      : 24;

    return {
      outstanding,
      ytdTotal,
      draftCount,
      avgDaysToPay: avgDays,
    };
  } catch (error) {
    console.error('Failed to compute billing metrics:', error);
    return { outstanding: 0, ytdTotal: 0, draftCount: 0, avgDaysToPay: 24 };
  }
}

export async function approveAllDrafts() {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false as const, error: 'FORBIDDEN', message: 'Forbidden' };
  const userId = await getCurrentUserId();
  try {
    const result = await prisma.invoice.updateMany({
      where: { userId, status: 'Draft' },
      data: { status: 'PendingApproval', approvedAt: new Date() },
    });
    revalidatePath('/billing');
    revalidatePath('/billing/approvals');
    return { success: true as const, message: `${result.count} invoice(s) submitted for approval.` };
  } catch (error) {
    console.error('Failed to approve all drafts:', error);
    return { success: false as const, error: 'UNKNOWN', message: 'Failed to approve drafts.' };
  }
}

export async function getInvoiceWithLineItems(id: string) {
  const userId = await getCurrentUserId();
  try {
    const row = await prisma.invoice.findFirst({
      where: { id, userId },
      include: {
        matter: { select: { title: true, clientName: true } },
        lineItems: true,
      },
    });
    if (!row) return null;
    return {
      id: row.id,
      invoiceNumber: row.invoiceNumber,
      matterId: row.matterId,
      matterTitle: row.matter.title,
      clientName: row.clientName,
      amount: Number(row.amount),
      dueDateLabel: row.dueDateLabel,
      notes: row.notes,
      status: row.status,
      createdAt: row.createdAt instanceof Date ? row.createdAt.toISOString() : String(row.createdAt),
      approvedAt: row.approvedAt instanceof Date ? row.approvedAt.toISOString() : null,
      lineItems: row.lineItems.map((li) => ({
        id: li.id,
        description: li.description,
        hours: Number(li.hours),
        rate: Number(li.rate),
        total: Number(li.total),
      })),
    };
  } catch (error) {
    console.error('Failed to fetch invoice with line items:', error);
    return null;
  }
}

type UpdateInvoiceInput = {
  invoiceNumber?: string;
  clientName?: string;
  amount?: number;
  dueDateLabel?: string;
  notes?: string;
  lineItems?: Array<{
    id?: string;
    description: string;
    hours: number;
    rate: number;
    total: number;
  }>;
};

export async function updateInvoice(invoiceId: string, data: UpdateInvoiceInput) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return { success: false as const, error: 'FORBIDDEN', message: 'Forbidden' };
  const userId = await getCurrentUserId();
  try {
    const inv = await prisma.invoice.findFirst({ where: { id: invoiceId, userId } });
    if (!inv) return { success: false as const, error: 'NOT_FOUND', message: 'Invoice not found.' };
    if (data.lineItems) {
      await prisma.$transaction([
        prisma.invoiceLineItem.deleteMany({ where: { invoiceId } }),
        prisma.invoiceLineItem.createMany({
          data: data.lineItems.map((li) => ({
            invoiceId,
            description: li.description,
            hours: new Prisma.Decimal(li.hours),
            rate: new Prisma.Decimal(li.rate),
            total: new Prisma.Decimal(li.total),
          })),
        }),
      ]);
    }

    const updated = await prisma.invoice.update({
      where: { id: invoiceId },
      data: {
        ...(data.invoiceNumber !== undefined ? { invoiceNumber: data.invoiceNumber } : {}),
        ...(data.clientName !== undefined ? { clientName: data.clientName } : {}),
        ...(data.amount !== undefined ? { amount: new Prisma.Decimal(data.amount) } : {}),
        ...(data.dueDateLabel !== undefined ? { dueDateLabel: data.dueDateLabel } : {}),
        ...(data.notes !== undefined ? { notes: data.notes } : {}),
      },
      include: { lineItems: true },
    });

    revalidatePath('/billing');
    revalidatePath(`/billing/${invoiceId}`);
    revalidatePath(`/billing/${invoiceId}/edit`);

    return {
      success: true as const,
      message: 'Invoice updated successfully.',
      invoice: {
        id: updated.id,
        invoiceNumber: updated.invoiceNumber,
        amount: Number(updated.amount),
        status: updated.status,
        lineItems: updated.lineItems.map((li) => ({
          id: li.id,
          description: li.description,
          hours: Number(li.hours),
          rate: Number(li.rate),
          total: Number(li.total),
        })),
      },
    };
  } catch (error) {
    console.error('Failed to update invoice:', error);
    return { success: false as const, error: 'UNKNOWN', message: 'Failed to update invoice.' };
  }
}

export async function getMattersForSelect() {
  const userId = await getCurrentUserId();
  try {
    const rows = await prisma.matter.findMany({
      where: { userId, status: 'Active' },
      select: { id: true, title: true, clientName: true, clientId: true },
      orderBy: { createdAt: 'desc' },
    });
    return rows;
  } catch (error) {
    console.error('getMattersForSelect error:', error);
    return [];
  }
}

/* ─── Billing Cycle / Auto-Generation ─── */

export async function getUnbilledTimeEntries(matterId: string) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return [];
  const userId = await getCurrentUserId();
  try {
    return await prisma.timeEntry.findMany({
      where: { matterId, userId, billable: true, invoiceId: null },
      orderBy: { date: 'asc' },
    });
  } catch (error) {
    console.error('getUnbilledTimeEntries error:', error);
    return [];
  }
}

export async function generateInvoiceFromTimeEntries(matterId: string, billingPeriodStart?: string, billingPeriodEnd?: string) {
  if (!await requireRole('PARTNER', 'ASSOCIATE')) return null;
  const userId = await getCurrentUserId();
  try {
    const matter = await prisma.matter.findFirst({ where: { id: matterId, userId } });
    if (!matter) return null;

    const unbilled = await prisma.timeEntry.findMany({
      where: { matterId, userId, billable: true, invoiceId: null },
      orderBy: { date: 'asc' },
    });
    if (unbilled.length === 0) return null;

    // Get effective rate from rate cards
    const { getEffectiveRate } = await import('@/app/actions/rateActions');
    const effectiveRate = await getEffectiveRate(matterId, matter.clientId ?? undefined);

    // Build line items — group by description if same, or keep individual
    const lineItems = unbilled.map((te) => ({
      description: te.description,
      hours: Number(te.hours),
      rate: effectiveRate,
      total: Number(te.hours) * effectiveRate,
    }));

    const totalAmount = lineItems.reduce((s, li) => s + li.total, 0);

    // Determine due date from client billing terms
    let dueLabel = 'Upon Receipt';
    if (matter.clientId) {
      const client = await prisma.client.findUnique({ where: { id: matter.clientId } });
      if (client?.billingTerms) {
        const termMap: Record<string, number> = {
          Net15: 15, Net30: 30, Net45: 45, Net60: 60, Net90: 90,
        };
        const days = termMap[client.billingTerms];
        if (days) {
          const due = new Date();
          due.setDate(due.getDate() + days);
          dueLabel = due.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        }
      }
    }

    const now = Date.now();
    const invoiceNumber = `AUTO-${matter.matterCode}-${now}`;

    const created = await prisma.invoice.create({
      data: {
        userId,
        invoiceNumber,
        matterId,
        clientName: matter.clientName,
        amount: new Prisma.Decimal(totalAmount),
        dueDateLabel: dueLabel,
        status: 'Draft',
        autoGenerated: true,
        billingPeriodStart: billingPeriodStart ? new Date(billingPeriodStart) : unbilled[0].date,
        billingPeriodEnd: billingPeriodEnd ? new Date(billingPeriodEnd) : unbilled[unbilled.length - 1].date,
        notes: 'Auto-generated from unbilled time entries.',
        lineItems: {
          create: lineItems.map((li) => ({
            description: li.description,
            hours: new Prisma.Decimal(li.hours),
            rate: new Prisma.Decimal(li.rate),
            total: new Prisma.Decimal(li.total),
          })),
        },
        timeEntries: {
          connect: unbilled.map((te) => ({ id: te.id })),
        },
      },
      include: { lineItems: true },
    });

    // Mark time entries as billed
    await prisma.timeEntry.updateMany({
      where: { id: { in: unbilled.map((te) => te.id) } },
      data: { billedAt: new Date(), invoiceId: created.id },
    });

    // Update matter's lastBillingDate
    await prisma.matter.update({
      where: { id: matterId },
      data: { lastBillingDate: new Date() },
    });

    revalidatePath('/billing');
    revalidatePath('/');
    return created;
  } catch (error) {
    console.error('generateInvoiceFromTimeEntries error:', error);
    return null;
  }
}

export async function runBillingCycleForUser(userId: string) {
  try {
    const firmProfile = await prisma.firmProfile.findFirst({ orderBy: { createdAt: 'asc' } });
    if (!firmProfile) return { generated: 0, message: 'No firm profile found.' };

    const cycleDays = firmProfile.billingCycleDays;
    const leadDays = firmProfile.billingLeadDays;

    // Find all active matters for this user
    const matters = await prisma.matter.findMany({
      where: { userId, status: 'Active' },
      select: {
        id: true, clientId: true, createdAt: true, lastBillingDate: true,
        billingCycleDays: true,
        _count: { select: { timeEntries: true } },
      },
    });

    const now = new Date();
    let generated = 0;

    for (const matter of matters) {
      // Skip matters with no time entries
      if (matter._count.timeEntries === 0) continue;

      // Check unbilled time entries exist
      const unbilledCount = await prisma.timeEntry.count({
        where: { matterId: matter.id, userId, billable: true, invoiceId: null },
      });
      if (unbilledCount === 0) continue;

      // Determine billing cycle for this matter (matter override or firm default)
      const effectiveCycle = matter.billingCycleDays ?? cycleDays;

      // Last billing date: if never billed, use matter creation date
      const lastDate = matter.lastBillingDate || matter.createdAt;
      const daysSinceLastBill = Math.round((now.getTime() - lastDate.getTime()) / (1000 * 60 * 60 * 24));

      // Check if we have passed the lead-time threshold AND at least one full cycle since last bill
      const triggerDays = effectiveCycle - leadDays;
      if (daysSinceLastBill < triggerDays) continue;
      if (daysSinceLastBill < effectiveCycle && matter.lastBillingDate !== null) continue;

      // Generate the invoice
      const result = await generateInvoiceFromTimeEntries(matter.id);
      if (result) generated++;
    }

    // Update lastBillingRun on firm profile
    await prisma.firmProfile.update({
      where: { id: firmProfile.id },
      data: { lastBillingRun: now },
    });

    revalidatePath('/');
    revalidatePath('/billing');
    return { generated, message: `Billing cycle complete. ${generated} invoice(s) generated.` };
  } catch (error) {
    console.error('runBillingCycle error:', error);
    return { generated: 0, message: 'Billing cycle failed.' };
  }
}

export async function runBillingCycle() {
  const userId = await getCurrentUserId();
  return runBillingCycleForUser(userId);
}

export async function getPendingAutoInvoices() {
  const userId = await getCurrentUserId();
  try {
    const rows = await prisma.invoice.findMany({
      where: { userId, autoGenerated: true, status: 'Draft' },
      orderBy: { createdAt: 'desc' },
      take: 10,
      include: { matter: { select: { title: true } } },
    });
    return rows.map((inv) => ({
      id: inv.id,
      invoiceNumber: inv.invoiceNumber,
      clientName: inv.clientName,
      matterTitle: inv.matter?.title ?? '',
      amount: Number(inv.amount),
      status: inv.status,
      billingPeriodStart: inv.billingPeriodStart?.toISOString() ?? null,
      billingPeriodEnd: inv.billingPeriodEnd?.toISOString() ?? null,
      createdAt: inv.createdAt instanceof Date ? inv.createdAt.toISOString() : String(inv.createdAt),
    }));
  } catch {
    return [];
  }
}

export async function getInvoices(filters?: {
  search?: string; status?: string; sortBy?: string; sortDir?: string; page?: number; clientId?: string;
}) {
  const userId = await getCurrentUserId();
  try {
    const where: Record<string, unknown> = { userId };

    if (filters?.clientId) where.matter = { clientId: filters.clientId };

    if (filters?.status) {
      const statuses = filters.status.split(',').map(s => s.trim()).filter(Boolean);
      if (statuses.length > 0) where.status = { in: statuses };
    } else {
      where.status = { in: ['Draft', 'PendingApproval'] };
    }

    if (filters?.search) {
      where.clientName = { contains: filters.search, mode: 'insensitive' };
    }

    const pageSize = 15;
    const page = Math.max(1, filters?.page ?? 1);
    const skip = (page - 1) * pageSize;

    const sortFieldMap: Record<string, string> = { invoiceNumber: 'invoiceNumber', amount: 'amount', status: 'status', createdAt: 'createdAt' };
    const sortField = sortFieldMap[filters?.sortBy ?? ''] || 'createdAt';
    const sortDir = filters?.sortDir === 'asc' ? 'asc' : 'desc';

    const [rows, totalCount] = await Promise.all([
      prisma.invoice.findMany({
        where,
        orderBy: { [sortField]: sortDir },
        skip,
        take: pageSize,
        include: {
          matter: { select: { id: true, title: true, clientId: true } },
        },
      }),
      prisma.invoice.count({ where }),
    ]);

    return {
      invoices: rows.map((row) => {
        const amount = Number(row.amount);
        return {
          id: String(row.id),
          invoiceNumber: row.invoiceNumber,
          clientName: row.clientName,
          amount,
          dueDate: row.dueDateLabel,
          status: row.status,
          createdAt: row.createdAt instanceof Date ? row.createdAt.toISOString() : String(row.createdAt),
          matterId: row.matter?.id ?? null,
          matterTitle: row.matter?.title ?? null,
          clientId: row.matter?.clientId ?? null,
        };
      }),
      totalCount,
      page,
      totalPages: Math.ceil(totalCount / pageSize),
    };
  } catch (error) {
    console.error('getInvoices error:', error);
    return { invoices: [], totalCount: 0, page: 1, totalPages: 0 };
  }
}
