'use client';

import React, { Suspense, useState, useRef, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { supabase } from '@/lib/supabase/client';
import { Shield, Loader2, CheckCircle, Lock, RotateCcw, KeyRound } from 'lucide-react';

export default function MFAPage() {
  return (
    <Suspense>
      <IdentityVerification />
    </Suspense>
  );
}

function IdentityVerification() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const factorId = searchParams.get('factorId');

  const [otp, setOtp] = useState(['', '', '', '', '', '']);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [challengeId, setChallengeId] = useState<string | null>(null);
  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  useEffect(() => {
    if (factorId) {
      supabase.auth.mfa.challenge({ factorId }).then(({ data, error }) => {
        if (error) setError(error.message);
        else setChallengeId(data.id);
      });
    }
  }, [factorId]);

  const handleChange = (element: React.ChangeEvent<HTMLInputElement>, index: number) => {
    if (isNaN(Number(element.target.value))) return;
    const newOtp = [...otp];
    newOtp[index] = element.target.value;
    setOtp(newOtp);
    if (element.target.value && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>, index: number) => {
    if (e.key === 'Backspace' && !otp[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!challengeId || !factorId) return;
    setError('');
    setLoading(true);

    const code = otp.join('');
    const { error } = await supabase.auth.mfa.verify({ factorId, challengeId, code });

    setLoading(false);
    if (error) {
      setError(error.message);
      setOtp(['', '', '', '', '', '']);
      inputRefs.current[0]?.focus();
    } else {
      setSuccess(true);
      setTimeout(() => router.push('/'), 1000);
    }
  };

  if (success) {
    return (
      <div className="bg-[#f8f9ff] text-[#0b1c30] min-h-dvh flex items-center justify-center px-4 overflow-y-auto py-12">
        <div className="text-center">
          <CheckCircle size={64} className="mx-auto text-[#15803d] mb-6" />
          <h2 className="font-headline-sm">Identity Confirmed</h2>
          <p className="text-[#46464d]">Accessing command center...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-[#f8f9ff] text-[#0b1c30] min-h-dvh flex flex-col overflow-y-auto">
      <div className="fixed inset-0 pointer-events-none opacity-5">
        <div className="absolute inset-0" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, #0b1c30 1px, transparent 0)', backgroundSize: '40px 40px' }}></div>
      </div>

      <main className="flex-grow flex items-center justify-center px-4 md:px-[48px] py-12 relative z-10">
        <div className="w-full max-w-[480px] flex flex-col items-center">
          <div className="mb-12 text-center">
            <h1 className="font-headline-lg text-[#000] uppercase">Kiya Law</h1>
            <div className="w-12 h-[2px] bg-[#735c00] mx-auto"></div>
          </div>

          <div className="w-full bg-white border border-[#c6c6ce] p-8 md:p-12 shadow-sm relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-1 bg-[#000]"></div>

            <div className="mb-10">
              <div className="flex items-center gap-3 mb-4">
                <Shield size={22} className="text-[#735c00]" />
                <span className="text-[14px] font-[600] uppercase tracking-widest text-[#46464d]">Security Protocol</span>
              </div>
              <h2 className="font-headline-md">High-Authority Verification</h2>
              <p className="text-[16px] text-[#46464d] leading-relaxed m-0">
                To access sensitive legal infrastructure and matter documentation, please enter the 6-digit code generated by your authenticator app.
              </p>
            </div>

            <form className="space-y-10" onSubmit={handleSubmit}>
              <div className="flex justify-between gap-2 md:gap-4">
                {otp.map((data, index) => (
                  <input
                    key={index}
                    ref={(el) => { inputRefs.current[index] = el; }}
                    className="w-full aspect-square text-center font-headline-md border-0 border-b-2 border-[#c6c6ce] bg-transparent focus:border-[#735c00] focus:ring-0 transition-all duration-300 outline-none text-[#0b1c30]"
                    type="text"
                    maxLength={1}
                    value={data}
                    onChange={(e) => handleChange(e, index)}
                    onKeyDown={(e) => handleKeyDown(e, index)}
                    inputMode="numeric"
                    pattern="[0-9]*"
                  />
                ))}
              </div>

              <div className="flex items-center space-x-3">
                <input className="w-5 h-5 border-[#c6c6ce] text-[#000] rounded-none focus:ring-0 cursor-pointer" id="trust-device" type="checkbox" />
                <label className="text-[14px] font-[600] text-[#0b1c30] cursor-pointer select-none" htmlFor="trust-device">
                  Trust this device for 30 days
                </label>
              </div>

              {error && (
                <div className="bg-[#ffdad6] border border-[#ba1a1a] text-[#93000a] px-4 py-3 text-[13px] font-medium">{error}</div>
              )}

              <div className="space-y-4">
                <button
                  className="w-full h-14 bg-[#000] text-white text-[14px] font-[600] uppercase tracking-widest hover:bg-[#0b1c30] transition-colors duration-200 border-none cursor-pointer flex justify-center items-center disabled:opacity-60"
                  type="submit"
                  disabled={loading || !challengeId}
                >
                  {loading ? (
                    <Loader2 size={20} className="animate-spin" />
                  ) : (
                    "Confirm Identity"
                  )}
                </button>
                <div className="flex flex-col items-center gap-4 pt-4 border-t border-[#c6c6ce]/30">
                  <button
                    className="text-[14px] font-[600] text-[#735c00] hover:underline tracking-widest uppercase transition-all bg-transparent border-none cursor-pointer flex items-center gap-2"
                    type="button"
                  >
                    <RotateCcw size={14} />
                    Resend Code
                  </button>
                  <button
                    className="text-[14px] font-[600] text-[#46464d]/70 hover:text-[#0b1c30] tracking-widest uppercase transition-all bg-transparent border-none cursor-pointer flex items-center gap-2"
                    type="button"
                  >
                    <KeyRound size={14} />
                    Use Backup Key
                  </button>
                </div>
              </div>
            </form>
          </div>

          <footer className="mt-12 text-center">
            <p className="text-[12px] font-[500] text-[#46464d] uppercase tracking-tighter opacity-50 m-0">
              Kiya Law Secure Gateway. ISO 27001 Certified Environment.
            </p>
          </footer>
        </div>
      </main>

      <div className="hidden lg:block fixed right-0 top-0 bottom-0 w-24 border-l border-[#c6c6ce] bg-[#f8f9ff]/30 pointer-events-none">
        <div className="h-full flex flex-col justify-between items-center py-12">
          <span className="text-[12px] font-[500] text-[#46464d] rotate-90 whitespace-nowrap opacity-30 tracking-[0.5em] origin-center">SYSTEM ENCRYPTION ACTIVE</span>
          <div className="flex flex-col gap-6 items-center">
            <div className="w-[1px] h-32 bg-[#c6c6ce]/50"></div>
            <Lock size={20} className="text-[#c6c6ce]" />
          </div>
        </div>
      </div>
    </div>
  );
}
