'use client';

import React, { useState, useRef, useCallback } from 'react';
import Link from 'next/link';
import { Pencil, Check, X } from 'lucide-react';
import AiTextAssistant from '@/components/ai/AiTextAssistant';

type LineItemData = {
  id?: string;
  description: string;
  hours: number;
  rate: number;
  total: number;
};

interface InvoiceDetailProps {
  invoiceNumber: string;
  client: string;
  clientId?: string | null;
  matter: string;
  matterId?: string;
  amount: string;
  dueDate: string;
  dateCreated: string;
  status: 'Draft' | 'Pending' | 'Approved' | 'Paid';
  lineItems?: LineItemData[];
  firm: { logoUrl: string | null; address: string | null; phone: string | null; email: string | null; website: string | null };
  clientAddress?: string | null;
  clientEmail?: string | null;
  clientPhone?: string | null;
  notes?: string | null;
  autoGenerated?: boolean;
  billingPeriodStart?: string | null;
  billingPeriodEnd?: string | null;
  stampActive: boolean;
  stampPosition: { right: number; bottom: number };
  onStampMove: (right: number, bottom: number) => void;
  onUpdateClientInfo?: (data: { address?: string; email?: string; phone?: string }) => void;
}

function formatAddress(addr: unknown): string {
  if (!addr) return '';
  if (typeof addr === 'string') return addr;
  if (typeof addr === 'object' && addr !== null) {
    const a = addr as Record<string, string>;
    const parts = [a.street, a.city, a.state, a.zip, a.country].filter(Boolean);
    return parts.join(', ');
  }
  return '';
}

export default function InvoiceDetail({
  invoiceNumber, client, clientId, matter, matterId, amount, dueDate, dateCreated,
  status, lineItems, firm, clientAddress, clientEmail, clientPhone, notes,
  autoGenerated, billingPeriodStart, billingPeriodEnd,
  stampActive, stampPosition, onStampMove, onUpdateClientInfo,
}: InvoiceDetailProps) {
  const [editingBillTo, setEditingBillTo] = useState(false);
  const [editAddress, setEditAddress] = useState(formatAddress(clientAddress));
  const [editEmail, setEditEmail] = useState(clientEmail || '');
  const [editPhone, setEditPhone] = useState(clientPhone || '');
  const cardRef = useRef<HTMLDivElement>(null);
  const dragRef = useRef<{ startX: number; startY: number; startRight: number; startBottom: number } | null>(null);

  const statusColors: Record<string, string> = {
    Draft: 'bg-[#eff4ff] border-[#c6c6ce] text-[#46464d]',
    Pending: 'bg-[#fff8e1] border-[#f9a825] text-[#e65100]',
    Approved: 'bg-[#e6f7e6] border-[#4caf50] text-[#2e7d32]',
    Paid: 'bg-[#e6f7e6] border-[#4caf50] text-[#2e7d32]',
  };

  const startEdit = useCallback(() => {
    setEditAddress(formatAddress(clientAddress));
    setEditEmail(clientEmail || '');
    setEditPhone(clientPhone || '');
    setEditingBillTo(true);
  }, [clientAddress, clientEmail, clientPhone]);

  const cancelEdit = useCallback(() => {
    setEditingBillTo(false);
  }, []);

  const saveEdit = useCallback(() => {
    onUpdateClientInfo?.({ address: editAddress, email: editEmail, phone: editPhone });
    setEditingBillTo(false);
  }, [editAddress, editEmail, editPhone, onUpdateClientInfo]);

  const handleStampMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    const card = cardRef.current;
    if (!card) return;
    const rect = card.getBoundingClientRect();
    dragRef.current = {
      startX: e.clientX,
      startY: e.clientY,
      startRight: stampPosition.right,
      startBottom: stampPosition.bottom,
    };

    const handleMove = (ev: MouseEvent) => {
      if (!dragRef.current || !card) return;
      const dx = dragRef.current.startX - ev.clientX;
      const dy = dragRef.current.startY - ev.clientY;
      const newRight = Math.max(0, Math.min(rect.width - 130, dragRef.current.startRight + dx));
      const newBottom = Math.max(0, Math.min(rect.height - 130, dragRef.current.startBottom + dy));
      onStampMove(newRight, newBottom);
    };

    const handleUp = () => {
      dragRef.current = null;
      window.removeEventListener('mousemove', handleMove);
      window.removeEventListener('mouseup', handleUp);
    };

    window.addEventListener('mousemove', handleMove);
    window.addEventListener('mouseup', handleUp);
  }, [stampPosition, onStampMove]);

  const displayAddress = editingBillTo ? editAddress : formatAddress(clientAddress);
  const displayEmail = editingBillTo ? editEmail : (clientEmail || '');
  const displayPhone = editingBillTo ? editPhone : (clientPhone || '');

  return (
    <div ref={cardRef} className="relative bg-white border border-[#c6c6ce] p-8 overflow-hidden">
      {/* Header */}
      <div className="flex justify-between items-start mb-4">
        <div>
          {firm.logoUrl || true ? (
            <img
              src={firm.logoUrl || '/Asset 1.png'}
              alt=""
              className="max-h-[60px] w-auto object-contain mb-2"
            />
          ) : null}
          <div className="text-[11px] text-[#46464d] leading-relaxed">
            {firm.address && <div>{firm.address}</div>}
            <div className="flex gap-2 flex-wrap">
              {firm.phone && <span>{firm.phone}</span>}
              {firm.phone && firm.email && <span className="text-[#c6c6ce]">|</span>}
              {firm.email && <span>{firm.email}</span>}
              {firm.email && firm.website && <span className="text-[#c6c6ce]">|</span>}
              {firm.website && <span>{firm.website}</span>}
            </div>
          </div>
        </div>
        <div className="text-right">
          <div className="text-[10px] text-[#7c839f] uppercase tracking-[2px] font-bold mb-1">Invoice</div>
          <div className="text-[22px] font-headline-sm text-[#0A1128]">{invoiceNumber}</div>
        </div>
      </div>

      {/* Divider */}
      <div className="border-t border-[#0A1128] mb-6" />

      {/* Bill To */}
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-[9px] text-[#7c839f] uppercase tracking-[1.5px] font-bold">Bill To</span>
          {!editingBillTo && (
            <button onClick={startEdit} className="text-[#D4AF37] hover:text-[#b8962e] transition-colors" title="Edit bill-to info">
              <Pencil size={12} />
            </button>
          )}
        </div>

        {editingBillTo ? (
          <div className="space-y-2">
            <div className="font-headline-sm text-[16px] text-[#0A1128]">{client}</div>
            <AiTextAssistant
              value={editAddress}
              onChange={setEditAddress}
              className="w-full text-[12px] border border-[#c6c6ce] p-1.5 outline-none resize-none"
              rows={2}
              placeholder="Street, City, State, ZIP"
            />
            <input
              value={editEmail}
              onChange={e => setEditEmail(e.target.value)}
              className="w-full text-[12px] border border-[#c6c6ce] p-1.5 rounded-none"
              placeholder="Email"
            />
            <input
              value={editPhone}
              onChange={e => setEditPhone(e.target.value)}
              className="w-full text-[12px] border border-[#c6c6ce] p-1.5 rounded-none"
              placeholder="Phone"
            />
            <div className="flex gap-2">
              <button onClick={saveEdit} className="flex items-center gap-1 text-[11px] font-bold uppercase tracking-wider bg-[#D4AF37] text-[#0A1128] px-3 py-1.5 rounded-none">
                <Check size={14} /> Save
              </button>
              <button onClick={cancelEdit} className="flex items-center gap-1 text-[11px] font-bold uppercase tracking-wider border border-[#c6c6ce] text-[#46464d] px-3 py-1.5 rounded-none">
                <X size={14} /> Cancel
              </button>
            </div>
          </div>
        ) : (
          <>
            <div className="font-headline-sm text-[16px] text-[#0A1128]">
              {clientId ? (
                <Link href={`/clients/${clientId}`} className="hover:text-[#D4AF37] underline underline-offset-2 transition-colors">{client}</Link>
              ) : client}
            </div>
            {displayAddress && <div className="text-[12px] text-[#46464d]">{displayAddress}</div>}
            <div className="text-[12px] text-[#46464d]">
              {displayEmail && <span>{displayEmail}</span>}
              {displayEmail && displayPhone && <span className="mx-1 text-[#c6c6ce]">|</span>}
              {displayPhone && <span>{displayPhone}</span>}
            </div>
          </>
        )}
      </div>

      {/* Matter + Dates */}
      <div className="flex justify-between items-end mb-6 pb-4 border-b border-[#c6c6ce]/50">
        <div>
          <div className="text-[9px] text-[#7c839f] uppercase tracking-[1.5px] font-bold mb-1">Matter</div>
          <div className="text-[13px] text-[#0A1128]">
            {matterId ? (
              <Link href={`/matters/${matterId}`} className="hover:text-[#D4AF37] underline underline-offset-2 transition-colors">{matter}</Link>
            ) : matter}
          </div>
          {autoGenerated && billingPeriodStart && (
            <div className="text-[10px] text-[#7c839f] mt-1">
              Period: {new Date(billingPeriodStart).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
              {billingPeriodEnd && ` — ${new Date(billingPeriodEnd).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`}
            </div>
          )}
        </div>
        <div className="text-right text-[11px] text-[#46464d]">
          <div><span className="text-[#7c839f]">Date:</span> {dateCreated}</div>
          <div><span className="text-[#7c839f]">Due:</span> {dueDate}</div>
        </div>
      </div>

      {/* Line Items */}
      <div className="mb-6">
        <div className="grid grid-cols-12 gap-2 text-[9px] text-[#7c839f] uppercase tracking-[1.5px] font-bold pb-2 border-b border-[#0A1128] mb-1">
          <div className="col-span-5">Description</div>
          <div className="col-span-2 text-right">Hours</div>
          <div className="col-span-2 text-right">Rate</div>
          <div className="col-span-3 text-right">Total</div>
        </div>

        {(!lineItems || lineItems.length === 0) ? (
          <div className="grid grid-cols-12 gap-2 py-2 text-[12px] text-[#0A1128] border-b border-[#c6c6ce]/30">
            <div className="col-span-5">Legal services</div>
            <div className="col-span-2 text-right">—</div>
            <div className="col-span-2 text-right">—</div>
            <div className="col-span-3 text-right">{amount}</div>
          </div>
        ) : (
          lineItems.map((li, idx) => (
            <div key={li.id || idx} className="grid grid-cols-12 gap-2 py-2 text-[12px] text-[#0A1128] border-b border-[#c6c6ce]/30">
              <div className="col-span-5">{li.description}</div>
              <div className="col-span-2 text-right">{li.hours.toFixed(1)}</div>
              <div className="col-span-2 text-right">{new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(li.rate)}</div>
              <div className="col-span-3 text-right">{new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(li.total)}</div>
            </div>
          ))
        )}

        {/* Totals */}
        <div className="flex justify-end mt-3">
          <div className="w-1/3">
            {lineItems && lineItems.length > 0 && (
              <div className="flex justify-between py-1 text-[12px] text-[#46464d]">
                <span>Subtotal</span>
                <span>{amount}</span>
              </div>
            )}
            <div className="flex justify-between py-1 text-[14px] font-bold text-[#0A1128] border-t border-[#0A1128] pt-2 mt-1">
              <span>Total</span>
              <span>{amount}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Notes */}
      {notes && (
        <div className="mb-6 p-3 bg-[#f8f9ff] border border-[#c6c6ce]/30 text-[12px] text-[#46464d]">
          <div className="text-[9px] text-[#7c839f] uppercase tracking-[1.5px] font-bold mb-1">Notes</div>
          {notes}
        </div>
      )}

      {/* Status + Auto-Generated badge */}
      <div className="flex justify-between items-center">
        <div className="flex items-center gap-3">
          <span className={`text-[10px] px-3 py-1 border font-bold uppercase tracking-widest ${statusColors[status]}`}>
            {status}
          </span>
          {autoGenerated && (
            <span className="text-[8px] font-bold uppercase tracking-widest bg-[#D4AF37]/10 text-[#735c00] px-2 py-1 border border-[#D4AF37]/30">
              Auto-Generated
            </span>
          )}
        </div>
      </div>

      {/* Stamp Overlay */}
      {stampActive && (
        <div
          onMouseDown={handleStampMouseDown}
          style={{
            position: 'absolute',
            right: stampPosition.right,
            bottom: stampPosition.bottom,
            width: 120,
            height: 120,
            transform: 'rotate(-12deg)',
            cursor: 'move',
            opacity: 0.85,
            zIndex: 10,
            userSelect: 'none',
          }}
          className="select-none"
        >
          <img src="/kiya-stamp.png" alt="" className="w-full h-full pointer-events-none" />
        </div>
      )}
    </div>
  );
}