'use client';

import React, { use, useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { ChevronRight, Printer, Download } from 'lucide-react';
import InvoiceDetail from '../../../../components/invoice/InvoiceDetail';
import { getInvoiceById, approveInvoice, finalizeInvoice, markAsPaid, rejectInvoice, updateInvoiceClientInfo } from '@/app/actions/billingActions';
import { getFirmProfile } from '@/app/actions/settingsActions';
import { useToastStore } from '../../../../lib/store/useToastStore';

type LineItemData = {
  id: string;
  description: string;
  hours: number;
  rate: number;
  total: number;
};

type InvoiceData = {
  id: string;
  invoiceNumber: string;
  matterId: string;
  matterTitle: string;
  clientName: string;
  clientId: string | null;
  amount: number;
  dueDateLabel: string;
  status: string;
  autoGenerated: boolean;
  billingPeriodStart: string | null;
  billingPeriodEnd: string | null;
  createdAt: string;
  approvedAt: string | null;
  notes: string | null;
  clientAddress: string | null;
  clientEmail: string | null;
  clientPhone: string | null;
  lineItems: LineItemData[];
};

type FirmData = {
  logoUrl: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
};

export default function InvoiceDetailsPage({ params }: { params: Promise<{ invoiceId: string }> }) {
  const { addToast, updateToast } = useToastStore();
  const resolvedParams = use(params);
  const [invoice, setInvoice] = useState<InvoiceData | null>(null);
  const [firm, setFirm] = useState<FirmData | null>(null);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState(false);
  const [stampActive, setStampActive] = useState(true);
  const [stampPosition, setStampPosition] = useState({ right: 30, bottom: 30 });

  useEffect(() => {
    Promise.all([
      getInvoiceById(resolvedParams.invoiceId),
      getFirmProfile(),
    ]).then(([invData, firmData]) => {
      if (invData) setInvoice(invData);
      if (firmData) {
        setFirm({
          logoUrl: firmData.logoUrl ?? null,
          address: firmData.address ?? null,
          phone: firmData.phone ?? null,
          email: firmData.email ?? null,
          website: firmData.website ?? null,
        });
      }
      setLoading(false);
    });
  }, [resolvedParams.invoiceId]);

  const handleStampMove = useCallback((right: number, bottom: number) => {
    setStampPosition({ right, bottom });
  }, []);

  const handleApprove = useCallback(async () => {
    if (actionLoading || !invoice) return;
    setActionLoading(true);
    const toastId = addToast('Submitting invoice for approval...', 'pending');
    const result = await approveInvoice(invoice.id);
    if (result.success) {
      updateToast(toastId, result.message, 'success');
      setInvoice((prev) => prev ? { ...prev, status: 'PendingApproval', approvedAt: new Date().toISOString() } : null);
    } else {
      updateToast(toastId, result.message, 'error');
    }
    setActionLoading(false);
  }, [invoice, actionLoading, addToast]);

  const handleFinalize = useCallback(async () => {
    if (actionLoading || !invoice) return;
    setActionLoading(true);
    const toastId = addToast('Finalizing invoice...', 'pending');
    const result = await finalizeInvoice(invoice.id);
    if (result.success) {
      updateToast(toastId, result.message, 'success');
      setInvoice((prev) => prev ? { ...prev, status: 'Finalized' } : null);
    } else {
      updateToast(toastId, result.message, 'error');
    }
    setActionLoading(false);
  }, [invoice, actionLoading, addToast]);

  const handleMarkAsPaid = useCallback(async () => {
    if (actionLoading || !invoice) return;
    setActionLoading(true);
    const toastId = addToast('Marking as paid...', 'pending');
    const result = await markAsPaid(invoice.id);
    if (result.success) {
      updateToast(toastId, result.message, 'success');
      setInvoice((prev) => prev ? { ...prev, status: 'Paid' } : null);
    } else {
      updateToast(toastId, result.message, 'error');
    }
    setActionLoading(false);
  }, [invoice, actionLoading, addToast]);

  const handleReject = useCallback(async () => {
    if (actionLoading || !invoice) return;
    setActionLoading(true);
    const toastId = addToast('Rejecting invoice...', 'pending');
    const result = await rejectInvoice(invoice.id);
    if (result.success) {
      updateToast(toastId, result.message, 'success');
      setInvoice((prev) => prev ? { ...prev, status: 'Draft' } : null);
    } else {
      updateToast(toastId, result.message, 'error');
    }
    setActionLoading(false);
  }, [invoice, actionLoading, addToast]);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  const handleDownloadPdf = useCallback(async () => {
    if (!invoice) return;
    try {
      const body = stampActive
        ? { pageStamps: { 0: { active: true, right: stampPosition.right, bottom: stampPosition.bottom } } }
        : {};
      const res = await fetch(`/api/invoice/${invoice.id}/export-pdf`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      if (!res.ok) throw new Error('PDF generation failed');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Invoice-${invoice.invoiceNumber}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      addToast('Failed to generate PDF. Please try again.', 'error');
    }
  }, [invoice, stampActive, stampPosition, addToast]);

  const handleUpdateClientInfo = useCallback(async (data: { address?: string; email?: string; phone?: string }) => {
    if (!invoice) return;
    const result = await updateInvoiceClientInfo(invoice.id, data);
    if (result.success) {
      addToast('Client info updated', 'success');
      setInvoice((prev) => prev ? {
        ...prev,
        clientAddress: data.address ?? prev.clientAddress,
        clientEmail: data.email ?? prev.clientEmail,
        clientPhone: data.phone ?? prev.clientPhone,
      } : null);
    } else {
      addToast(result.message, 'error');
    }
  }, [invoice, addToast]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-b border-b-2 border-[#0A1128]"></div>
      </div>
    );
  }

  if (!invoice) {
    return (
      <div className="px-margin-mobile md:px-margin-desktop py-8 md:py-12 max-w-5xl mx-auto w-full">
        <div className="text-center py-20">
          <h2 className="font-headline-sm">Invoice Not Found</h2>
          <Link href="/billing" className="text-[#D4AF37] hover:underline font-label-md text-[13px] font-bold uppercase tracking-wider">
            Back to Billing
          </Link>
        </div>
      </div>
    );
  }

  const displayId = invoice.invoiceNumber;

  const detailProps = {
    invoiceNumber: `#${invoice.invoiceNumber}`,
    client: invoice.clientName,
    clientId: invoice.clientId,
    matter: invoice.matterTitle,
    matterId: invoice.matterId,
    amount: new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(invoice.amount),
    dueDate: invoice.dueDateLabel || 'Upon Receipt',
    dateCreated: new Date(invoice.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    status: (
      invoice.status === 'PendingApproval' ? 'Pending' :
      invoice.status === 'Finalized' ? 'Approved' :
      invoice.status
    ) as 'Draft' | 'Pending' | 'Approved' | 'Paid',
    lineItems: invoice.lineItems,
    firm: firm || { logoUrl: null, address: null, phone: null, email: null, website: null },
    clientAddress: invoice.clientAddress,
    clientEmail: invoice.clientEmail,
    clientPhone: invoice.clientPhone,
    notes: invoice.notes,
    autoGenerated: invoice.autoGenerated,
    billingPeriodStart: invoice.billingPeriodStart,
    billingPeriodEnd: invoice.billingPeriodEnd,
    stampActive,
    stampPosition,
    onStampMove: handleStampMove,
    onUpdateClientInfo: handleUpdateClientInfo,
  };

  const isDraft = invoice.status === 'Draft';
  const isPending = invoice.status === 'PendingApproval';
  const isFinalized = invoice.status === 'Finalized';
  const showStampToggle = isFinalized || invoice.status === 'Paid';

  return (
    <div className="flex flex-col min-h-full relative pb-24">
      {/* Main Canvas */}
      <div className="flex-1 px-6 md:px-12 py-8 md:py-12 max-w-5xl mx-auto w-full">
        
        {/* Breadcrumbs */}
        <nav aria-label="Breadcrumb" className="flex text-[#46464d] font-label-sm text-[12px] font-bold uppercase tracking-widest mb-8">
          <ol className="inline-flex items-center gap-2">
            <li className="inline-flex items-center">
              <Link href="/billing" className="hover:text-[#0A1128] transition-colors">Invoices</Link>
            </li>
            <li>
              <ChevronRight size={14} className="text-[#c6c6ce]" />
            </li>
            <li aria-current="page">
              <span className="text-[#0A1128] font-bold">#{displayId}</span>
            </li>
          </ol>
        </nav>

        {/* Header Section */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-10 border-b border-[#c6c6ce]/40 pb-6">
          <div className="flex items-center gap-4">
            <h2 className="font-headline-md">{isDraft ? 'Draft' : isPending ? 'Pending Approval' : 'Invoice'} Details
            </h2>
            <span className={`px-3 py-1 border font-label-sm text-[11px] font-bold uppercase tracking-widest rounded-none ${isFinalized ? 'bg-[#e6f7e6] border-[#4caf50] text-[#2e7d32]' : 'bg-[#eff4ff] border-[#c6c6ce] text-[#46464d]'}`}>
              {invoice.status}
            </span>
          </div>
          <div className="flex items-center gap-4">
            <button onClick={handlePrint} className="flex items-center gap-2 text-[#46464d] hover:text-[#0A1128] transition-colors">
              <Printer size={18} />
              <span className="font-label-md text-[13px] font-bold uppercase tracking-wider">Print</span>
            </button>
            {showStampToggle && (
              <label className="flex items-center gap-1.5 cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={stampActive}
                  onChange={e => setStampActive(e.target.checked)}
                  className="accent-[#D4AF37] w-3.5 h-3.5"
                />
                <span className="font-label-sm text-[11px] font-bold uppercase tracking-wider text-[#46464d]">Stamp</span>
              </label>
            )}
            <button onClick={handleDownloadPdf} className="flex items-center gap-2 text-[#46464d] hover:text-[#0A1128] transition-colors">
              <Download size={18} />
              <span className="font-label-md text-[13px] font-bold uppercase tracking-wider">Download PDF</span>
            </button>
          </div>
        </div>

        <InvoiceDetail {...detailProps} />

        {/* Terms & Notes */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-[#46464d] font-body-md text-[13px] mb-8 mt-8">
          <div>
            <h4 className="font-label-sm text-[11px] font-bold text-[#7c839f] uppercase tracking-widest mb-2">Terms & Conditions</h4>
            <p className="leading-relaxed">Payment is due within 30 days of final invoice date. Late payments may be subject to a 1.5% monthly interest fee.</p>
          </div>
          <div>
            <h4 className="font-label-sm text-[11px] font-bold text-[#7c839f] uppercase tracking-widest mb-2">Wire Instructions</h4>
            <p className="leading-relaxed">Please remit payment to: Kiya Law Operating Account<br/>Routing: 021000021 | Acct: *******8923</p>
          </div>
        </div>
      </div>

      {/* Fixed Footer Action Bar */}
      <footer className="fixed bottom-0 right-0 left-0 md:left-20 lg:left-64 bg-white border-t border-[#c6c6ce]/50 shadow-[0_-4px_20px_rgba(10,17,40,0.05)] p-4 md:p-6 z-40 transition-all duration-300">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-4">
          
          <Link href="/billing" className="w-full sm:w-auto font-label-md text-[13px] font-bold uppercase tracking-wider text-red-600 hover:text-red-800 transition-colors px-4 py-3 text-center rounded-none">
            {isDraft ? 'Discard Draft' : 'Back to Billing'}
          </Link>
          
          <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
            {isDraft && (
              <Link href={`/billing/${resolvedParams.invoiceId}/edit`} className="w-full sm:w-auto font-label-md text-[13px] font-bold uppercase tracking-wider border border-[#0A1128] text-[#0A1128] hover:bg-[#f8f9ff] transition-colors px-8 py-3.5 text-center rounded-none">
                Edit Invoice
              </Link>
            )}
            {isDraft && (
              <button
                onClick={handleApprove}
                disabled={actionLoading}
                className="w-full sm:w-auto font-label-md text-[13px] font-bold uppercase tracking-wider bg-[#D4AF37] text-[#0A1128] hover:bg-[#ffe088] transition-colors px-10 py-3.5 shadow-md text-center rounded-none disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {actionLoading ? 'Submitting...' : 'Approve & Finalize'}
              </button>
            )}
            {isPending && (
              <>
                <button
                  onClick={handleReject}
                  disabled={actionLoading}
                  className="w-full sm:w-auto font-label-md text-[13px] font-bold uppercase tracking-wider border border-red-600 text-red-600 hover:bg-red-50 transition-colors px-8 py-3.5 text-center rounded-none disabled:opacity-60 disabled:cursor-not-allowed"
                >
                  {actionLoading ? 'Rejecting...' : 'Reject'}
                </button>
                <button
                  onClick={handleFinalize}
                  disabled={actionLoading}
                  className="w-full sm:w-auto font-label-md text-[13px] font-bold uppercase tracking-wider bg-[#0A1128] text-white hover:bg-[#162244] transition-colors px-10 py-3.5 shadow-md text-center rounded-none disabled:opacity-60 disabled:cursor-not-allowed"
                >
                  {actionLoading ? 'Finalizing...' : 'Finalize Invoice'}
                </button>
              </>
            )}
            {isFinalized && invoice.status !== 'Paid' && (
              <button
                onClick={handleMarkAsPaid}
                disabled={actionLoading}
                className="w-full sm:w-auto font-label-md text-[13px] font-bold uppercase tracking-wider bg-[#059669] text-white hover:bg-[#047857] transition-colors px-10 py-3.5 shadow-md text-center rounded-none disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {actionLoading ? 'Processing...' : 'Mark as Paid'}
              </button>
            )}
          </div>
          
        </div>
      </footer>
    </div>
  );
}